server:
  servlet:
    context-path: /java8
  port: 8080
spring:
  application:
    name: Java_8
  profiles:
    include: @profiles.active@
# jasypt加密的密匙
jasypt:
  encryptor:
    password: 8y37J6qFKQnuQyKr9y
