spring:
  application:
    name: SocketTransferServer
  profiles:
    include: @profiles.active@
server:
  servlet:
    context-path: /socket-transfer-server
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.cloud.openfeign.FeignClient: DEBUG
    # 或者为特定 Feign 客户端设置日志级别
    # your.package.YourFeignClient: DEBUG
feign:
  client:
    config:
      default: # 默认配置
        loggerLevel: FULL # 设置 Feign 的日志级别
      # 或者为特定客户端设置
      # yourClientName:
        # loggerLevel: FULL