server:
  servlet:
    context-path: /socket-transfer-server
spring:
  application:
    name: SocketTransferServer
  profiles:
    include: @profiles.active@
springdoc:
  swagger-ui:
    path: /swagger-ui.html