server:
  port: ${env.port.sts}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    # 为特定 Feign 客户端设置日志级别
    # com.mdsd.cloud.feign: DEBUG
feign:
  client:
    config:
      default: # 默认配置
        loggerType: FULL # 设置 Feign 的日志级别
        # 或者为特定客户端设置
        # yourClientName:
        # loggerLevel: FULL
# 服务器环境IP&PORT配置
env:
  ip:
    tyjw_server: 192.168.0.222
  port:
    sts: 20240
    web-socket-server: 20241
    tyjw_api: 12000
    tyjw_socket: 13002