server:
  servlet:
    context-path: /socket-transfer-server
  tomcat:
    max-connections: 109 # max-threads + accept-count
    connection-timeout: 20000
    threads:
      max: 9 # (2 x CPU Cores) + 1 或 (3 x CPU Cores) + 1
      min-spare: 5 # 低负载设置 5 高负载可设置成 max 数
spring:
  application:
    name: SocketTransferServer
  profiles:
    include: @profiles.active@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
#      file-size-threshold: 65535B

springdoc:
  swagger-ui:
    path: /swagger-ui.html
minio:
  endpoint: http://192.168.0.221:9000
  access-key: 0a75wAuJjOu4eDM2xw2p
  secret-key: s2ZvhoPCUnFLldFtRDTl9VRxv5TEzmoQc5dZYeUC
  bucket-name: mdsd-m350