server:
  port: ${env.port.sts.api}
  ssl:
    # 填写jks-password.txt文件内的密码
    key-store-password: 123456
    # JKS格式证书密钥库类型,PFX格式的证书密钥库类型为PKCS12
    key-store-type: JKS
    # 您需要使用实际的证书名称替换domain_name.jks
    key-store: classpath:keystore.jks